---
title: "Initial exploration of scraping capabilities in HMDD"
author: "João Vitor"
date: "09/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
```

## Scraping HMDD

Refactor calls/url building that are common to both functions, get info from diseases too.

```{r}
make_request <- function(url) {
  tryCatch(
    {
      message("Processing the request...")
      xml2::read_html(url)
    },
    error = function(cond) {
      message(paste("The URL does not seem to exist:", url))
      return(NULL)
    }
  )
}


get_hmdd_content <- function(url, obj_xpath) {
  tryCatch(
    {
      req <- make_request(url) %>%
        rvest::html_node(xpath = obj_xpath) %>%
        rvest::html_attr("href")
      paste0("http://www.cuilab.cn", req) %>%
        readLines()
    },
    error = function(cond) {
      message(paste("Couldn't find the required information!"))
      return(NULL)
    }
  )
}

make_hmdd_url <- function(info_type, id, extra_id) {
  sprintf("http://www.cuilab.cn/hmdd3app/%s/%s_%s/", info_type, id, extra_id)
}
```

```{r}
get_hmdd_causality <- function(entity) {
  if (startsWith(entity, "hsa")) {
    url <- make_hmdd_url("causality", entity, "a3")
  } else {
    encoded_disease <- URLencode(tools::toTitleCase(entity))
    url <- make_hmdd_url("causality", encoded_disease, "a4")
  }

  result <- get_hmdd_content(url, '//*[@id="browsedownload"]')

  table <- readr::read_tsv(result[2:length(result)]) %>%
    dplyr::mutate(entity_name = gsub("miRNA name:\t|Disease name:\t", "", result[1]))
}
```

```{r}
get_hmdd_net <- function(entity) {
  if (startsWith(entity, "hsa")) {
    url <- make_hmdd_url("browse_net", tolower(entity), "n1")
  } else {
    encoded_disease <- URLencode(tools::toTitleCase(entity))
    url <- make_hmdd_url("browse_net", encoded_disease, "n2")
  }

  result <- get_hmdd_content(url, "/html/body/p/b/span[2]/a") %>%
    readr::read_tsv()
}
```


```{r testing-hmdd}
sepsis <- get_hmdd_causality("sepsis")
silicosis_net <- get_hmdd_net("silicosis")

hm101 <- get_hmdd_causality("hsa-mir-101")
hm101_net <- get_hmdd_net("hsa-mir-101")
```

# Scraping mirTarBase

```{r}
get_mirtar_disease <- function(disease) {
  base <- "http://mirtarbase.cuhk.edu.cn/php/search.php?opt=disease_intermediate_mirna&disease_mirna="

  url <- paste0(base, disease)

  result <- make_request(url)

  result %>%
    rvest::html_table() %>%
    "[["(1)
}
```

```{r testing-mirtar}
carci <- get_mirtar_disease("Carcinoma")
```
